import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/page";
import Body from "./components/Body/page";
import Options from "./components/Options.jsx/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Body />
        <Options />
        {children}
      </body>
    </html>
  );
}
